### ISSUE TITLE
Add note to README that `docker-compose up` won't work when other postgres is running

### ISSUE THREAD

**Issue by kylebarron** [stac-utils/arturo-stac-api#63]
I kept getting 
```
stac-api     | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  role "username" does not exist
```
when running `docker-compose up`.

It turned out (with help from [this SO answer](https://stackoverflow.com/a/48594038)) that I had a global system Postgres on my Mac that was also running on port 5432. So the Postgres in Docker was being hidden by the system Postgres. When I shut down the system postgres, `docker-compose up` worked.

**Comment by geospatial-jeff** [comment]
closing this with #101 (thanks @bitner!)
